### ISSUE TITLE
Decide which gauge value to set when user gives feedback

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#115]
From pull request #114 

**What value of the gauge (from throughout the day) do we want to present to the user when the user is giving feedback?**
 * the most extreme (extreme based on what definition)?
* the latest? 
 * the first?

**Comment by Chuansi-LU** [comment]
Not sure if this is the right Place to provide comments/feedback on version 1.2.0. 

1.	Great to see the additions of user instructions and clothing module. Feedback under Settings is also working.
2.	I am not sure what is the best way to provide my comments, through GutHub, email or Feedback button under Settings?
3.	When I try to write texts in the Feedback window under Settings, the pop up keyboard blocks the window.
4.	“Acclimatization” (more precisely it should be “Acclimatization to Heat”) under Settings: the pop up texts indicate acclimatization to working environment. The definition according to WBGT standard is “a person has been exposed to the hot working conditions for at least one full working week immediately prior to the assessment period”. Thus, “hot”, “at least one week” are important and should be included in the definition.
5.	I still think “Headgear” should be part of Clothing ensembles. If Headgear is highlighted, should we add also Footwear, Gloves here?
6.	I tried to adjust my predicted thermal stress score under Feedback. But this adjustment e.g. -0.6 is always showing on the Dashboard – “Based on your feedback, your heat stress score is adjusted by -0.6 relative to average”. I cannot get rid of it. How can I adjust it back?
7.	The button on Dashboard to “< update weather”: I am not sure if I should slide or click? can it be updated so that once I come back from Settings to Dashboard, the weather is automatically updated? It does not seem to function in this way.
8.	Ta was 26 C when I tried the app today. Under the info for experienced users, Windchill is also given, 28 C. I think this info is not needed. Wind chill is used for cold environments, < 10 C.
9.	A suggestion for the next update: make it possible to allow users to input their metabolic rate, local microclimate temperature, clothing insulation, if the users measure them precisely.
10.	 Under the info for experienced users, suggest changing “Evaporation impairment” to “Moisture permeability index (im)”. Im for sport clothes, typical summer clothing (e.g. T-shirt, shorts, socks and shoes) is 0.42 (higher than 0.38).
11.	More Info -> User: 3 WBGT values are provided. Not sure if it can make some users confused. I think when clothing is taken into consideration in WBGT adjustment, WBGT_effective (not WBGT) should be used. 
12.	More info -> PHS: when body core temperature is expected to exceed 38 C in 30 min, we can add a suggestion “take a rest after 30 min work”. when total sweat rate is calculated, .e.g. 0.9 L/h, a hydration suggestion can be added, like “You need to drink about 0.9 L water per hour”.
