### ISSUE TITLE
Navigation icons

### ISSUE THREAD

**Issue by FritzdorfSport** [frksteenhoff/ClimApp#144]
**Describe the bug**
I press the house icon to go Home (back to the Dashboard)

**Comment by Chuansi-LU** [comment]
I also got the same comment from other users and from the usability test. We need to find a solution e.g. 1. a better Icon. 2. put Indoor and outdoor mode selection under Settings, 3. on Dashboard/righ upper corner, modify the text "Outdoor/Indoor" so that it is clickable. when clicked, the text will switch between Outdoor and Indoor mode.

**Comment by Chuansi-LU** [comment]
I also got the same comment from other users and from the usability test. We need to find a solution e.g. 1. a better Icon. 2. put Indoor and outdoor mode selection under Settings, 3. on Dashboard/righ upper corner, modify the text "Outdoor/Indoor" so that it is clickable. when clicked, the text will switch between Outdoor and Indoor mode.

**Comment by Chuansi-LU** [comment]
I also got the same comment from other users and from the usability test. We need to find a solution e.g. 1. a better Icon. 2. put Indoor and outdoor mode selection under Settings, 3. on Dashboard/righ upper corner, modify the text "Outdoor/Indoor" so that it is clickable. when clicked, the text will switch between Outdoor and Indoor mode.

**Comment by BorisKingma** [comment]
indoor / outdoor is now arranged via homescreen. - including user input for thermal environment (indoor only)
