### ISSUE TITLE
Settings or Preferences?

### ISSUE THREAD

**Issue by FritzdorfSport** [frksteenhoff/ClimApp#146]
In the same way that a house icon is usually used to indicate Home (see my earlier report), a cog icon is usually "Settings".

Tapping on the cog gives "Preferences", and yet there is only one preference/setting ("Units")

"Settings" are more difficult to find - through Dashboard-Personal-Info

**Comment by Chuansi-LU** [comment]
Personal settings under Info is a way to personalse the app. On the other hand, these personal information was usually input when the user installed the app.  If Age, Height, Weight, Sex are placed under Settings (users inputs when they install the app), then "Acclimatisation" can be lifted up to the same row as Activity and Clothing because these are personal factors used to personalize the app. Alternatively, change "Info" to "Personal Info", and put under both Customization and Settings.

**Comment by BorisKingma** [comment]
Personal info is labeled: body
Cog icon has been replaced by bars (3 horizontal bars)
Home icon has been removed as indoor mode is now part of main dashboard
